# version format
version: "{branch}-{build}"

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# Build on x64 only
platform: x64

environment:
  SFDX_URL_WINDOWS: https://developer.salesforce.com/media/salesforce-cli/sfdx-cli/channels/stable/sfdx-cli-windows-x64.tar.xz
  SFDX_AUTOUPDATE_DISABLE: true
  SFDX_DOMAIN_RETRY: 300

install:
  - curl -fsSL -o sfdx-windows-amd64.tar.xz %SFDX_URL_WINDOWS%
  - 7z x sfdx-windows-amd64.tar.xz
  - 7z x sfdx-windows-amd64.tar
  - ps: $env:Path += ";" + (Get-ChildItem -Filter "sfdx-cli-*" -Directory).Fullname + "\bin"
  - ps: echo $env:Path

build_script:
  - ps: Get-MpPreference

# Just try to invoke and echo out the sfdx version
test_script:
  - sfdx version

# Uncomment if you want to RDP into the machine to debug this
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
 
